### ISSUE TITLE
Tried to search a map and seems website broke

### ISSUE THREAD

**Issue by Pallid3** [yorunoken/map-analyzer#1]
I tried to analyze Jashin (https://osu.ppy.sh/beatmapsets/1923289#osu/3970329) and it returned nothing it seems. I added screen recording as well.

https://github.com/user-attachments/assets/17bc8348-c89c-4ca7-b9c4-2c41a1750e2d

**Comment by yorunoken** [comment]
Found the issue, the BPM calculator I wrote isn't working correctly and thought it was 180BPM instead of 240, will deploy a fix in a bit
