### ISSUE TITLE
Deathstream maps reports incorrect values

### ISSUE THREAD

**Issue by Coppertine** [yorunoken/map-analyzer#2]
Beatmap 1: https://osu.ppy.sh/beatmapsets/2251537#osu/4788524
(Beatmap shown is ONLY streams (3-4 deathstreams), no jumps)
Jumps reports as primary (100% confidence) with stream secondary (100% confidence), (expected Stream primary)
Longest Stream reports incorrect value (expected: 796 notes, given: 199 notes, possibly due to cutstreams)

Beatmap 2: https://osu.ppy.sh/beatmapsets/1474871#osu/3082637
(Ending includes a long deathstream)
Streams correctly reported as primary.
Longest Stream however reports incorrect value (expected: 569 notes, given: 199 notes, this could mean that longest streams are capped at 199 notes)

Beatmap 3: https://osu.ppy.sh/beatmapsets/724192#osu/1529189
Streams correctly reported as primary.
Longest Stream however reports incorrect value (expected: 409 notes, given: 199 notes, validates this theory quite a bit.)

**Comment by yorunoken** [comment]
Hello, yes, I remember keeping the  window of searching to 200. I should definitely remove that cap as it leads to confusion on maps with long patterns, thank you for bringing this to my attention!

as for beatmap 1, I'll see what's wrong with it and get back to you here!
